import type { StylePreset } from "./styleTypes";
import atlantaTrapArt from "./assets/templates/atlanta-trap.webp";
import brooklynDrillArt from "./assets/templates/brooklyn-drill.webp";
import eastCoastBoomBapArt from "./assets/templates/east-coast-boom-bap.webp";
import popRapArt from "./assets/templates/pop-rap.webp";
import latinPopArt from "./assets/templates/latin-pop.webp";
import corridosArt from "./assets/templates/corridos.webp";
import reggaeArt from "./assets/templates/reggae.webp";
import soulRnbArt from "./assets/templates/soul-rnb.webp";
import gospelArt from "./assets/templates/gospel.webp";
import cafeBossaArt from "./assets/templates/cafe-bossa.webp";
import contemporaryFolkArt from "./assets/templates/contemporary-folk.webp";
import heroicTrailerArt from "./assets/templates/heroic-trailer.webp";
import fantasyAdventureArt from "./assets/templates/fantasy-adventure.webp";
import bedtimeLullabyArt from "./assets/templates/bedtime-lullaby.webp";
import cuteCharacterArt from "./assets/templates/cute-character.webp";
import hairBandArt from "./assets/templates/80s-hair-band.webp";
import techno80sArt from "./assets/templates/80s-techno.webp";

export const EXTRA_TEMPLATE_ART: Record<string, string> = {
  "Atlanta trap": atlantaTrapArt,
  "Brooklyn drill": brooklynDrillArt,
  "East Coast boom bap": eastCoastBoomBapArt,
  "Pop rap": popRapArt,
  "Latin pop": latinPopArt,
  Corridos: corridosArt,
  Reggae: reggaeArt,
  "Soul R&B": soulRnbArt,
  Gospel: gospelArt,
  "Cafe bossa nova": cafeBossaArt,
  "Contemporary folk": contemporaryFolkArt,
  "Heroic trailer cue": heroicTrailerArt,
  "Fantasy adventure cue": fantasyAdventureArt,
  "Bedtime lullaby": bedtimeLullabyArt,
  "Cute character theme": cuteCharacterArt,
  "80s hair band": hairBandArt,
  "80s techno": techno80sArt,
};

export const EXTRA_STYLE_PRESETS: Record<string, StylePreset> = {
  "Atlanta trap": { genre: "English, Atlanta trap with dark space, sliding 808s and clipped hi-hats rather than boom-bap or drill", tempo: "140 BPM, F minor, half-time 4/4 with a rolling 808 pull and no four-on-the-floor house groove", mood: "Late-night swagger, expensive stillness, a taunting hook, a brief mute, then a colder final verse", voice: "Singer A (Male), a gravel-leaning rap-sung lead with Atlanta cadence, short ad-libs and a memorable sung hook", delivery: "Rhythmic verses, a sung chorus hook, sparse ad-libs. No East Coast boom-bap flow, UK drill slide, or pop-R&B crooning", arrangement: "Sliding 808, sparse dark keys and a dry trap kit from bar one. A bell or flute motif answers the hook. Mute drums for one bar, then the 808 returns harder", production: "Dark expensive mix, huge centered sub, crisp hats, vocal-forward hook. No rock guitar, house four-on-the-floor, orchestral trailer hit or phonk cowbell" },
  "Brooklyn drill": { genre: "English, Brooklyn drill with off-grid sliding 808s, stalking kicks and a gravel street vocal rather than UK drill or Atlanta trap", tempo: "144 BPM, C-sharp minor, stalking 4/4 with delayed 808 slides and no bounce-trap swing", mood: "Cold sidewalk pressure, clipped threats, a chantable hook, a sudden drop-out, then a harder last 16", voice: "Singer A (Male), a dry Brooklyn drill lead with gravel, short bars and a gang-answer on selected hook words", delivery: "Staccato bars locked to the slide. Hook is chanted more than sung. No melody-rap pop, UK roadman parody or sung R&B", arrangement: "Off-grid kick, sliding 808 and a tense two-note ostinato. Open hats and a distant siren texture. Strip to 808 and voice, then restore the ostinato", production: "Dry street mix, aggressive transients, narrow verse and wider hook. No UK drill sample pack cliché, Memphis phonk, EDM drop or live band" },
  "East Coast boom bap": { genre: "English, East Coast boom bap with dusty chops, hard snare and dense rhyme rather than trap or lo-fi beats", tempo: "93 BPM, D minor, swung boom-bap pocket with a dry acoustic snare and no 808 slide", mood: "Block-cipher confidence, vivid city detail, a head-nod hook, a short scratch break, then a final verse that lands the argument", voice: "Singer A (Male), a dense East Coast rap lead with clear consonants, internal rhyme and a punch-in cadence", delivery: "Written bars, no sung chorus required; a short chant hook is enough. No trap ad-lib parade, pop-rap melody or spoken-word softness", arrangement: "Dusty sampled chords, hard kick-snare, vinyl-leaning bass. A scratch or horn stab answers the hook. Drop to drums and voice for eight bars, then the chop returns", production: "Warm dusty mix, present snare, modest sub, no sliding 808, drill hats, EDM riser or glossy pop stack" },
  "Pop rap": { genre: "English, radio pop rap with calm sung verses and a polished melodic hook rather than underground boom-bap or trap-only cadences", tempo: "96 BPM, A minor, mid-tempo 4/4 with a half-time chorus lift", mood: "Cool confidence, a conversational verse, a catchy sung hook, a cooler bridge, then a double chorus", voice: "Singer A (Male), a light rap-sung tenor with radio diction, easy melody and a memorable hook voice", delivery: "Sung-rap verses, a clearly sung chorus, light doubles on the hook. No dense lyricist flex, drill slide or rock scream", arrangement: "Punchy drums, rounded bass and a simple guitar or piano figure. Chorus opens with a synth or vocal chop hook. Bridge strips to pulse and voice", production: "Loud clean radio mix, vocal-forward, tight low end. No dusty boom-bap, dark drill, metal guitar or festival EDM drop" },
  "Latin pop": { genre: "Spanish, contemporary Latin pop with humidity, syncopated guitar and a danceable chorus rather than reggaeton dembow takeover or corridos beats", tempo: "102 BPM, G minor, mid-tempo 4/4 with a syncopated guitar-and-percussion pocket", mood: "Warm night invitation, playful verses, a communal singalong hook, a brief breakdown, then a glowing last chorus", voice: "Singer A (Female), a bright Latin-pop mezzo with clear Spanish diction, easy upper mix and smiling vowels", delivery: "Melodic verses, a chantable chorus, light unison doubles. No rap verse requirement, ranchera belt or English-only pop", arrangement: "Nylon or clean electric guitar, congas or palmas-leaning percussion, rounded bass. Pre-chorus adds claps; chorus opens wide. Drop to guitar and voice, then the final chorus", production: "Warm glossy mix, present vocal, sunlit stereo. No heavy dembow kick, norteño accordion lead, trap 808 slide or rock distortion", language: "es" },
  Corridos: { genre: "Spanish, contemporary corridos tumbados with acoustic guitar story-song character, tuba or bass punch and a narrative hook rather than generic Latin pop or trap", tempo: "118 BPM, A minor, mid-tempo 4/4 with a sierreño guitar lilt and a heavier chorus pocket", mood: "Dust-road narrative, cool bravado, a memorable sung hook, a guitar conversation, then a dry last line", voice: "Singer A (Male), a close Mexican-Spanish tenor with story-first phrasing, light rasp and regional cadence", delivery: "Narrative verses, a singable chorus, no pop-rap cadence or operatic belt", arrangement: "Requinto-style guitar and 12-string textures open. Tuba or synth-bass and a dry kit enter for the chorus. A short guitar break, then voice and guitar close", production: "Present vocal, bright acoustic guitars, punchy low end. No EDM drop, dembow, orchestra or English Top-40 sheen", language: "es" },
  Reggae: { genre: "English, contemporary roots reggae with offbeat skank, round bass and unhurried pocket rather than dancehall dembow or ska-punk", tempo: "78 BPM, A minor, laid-back 4/4 with a heavy one-drop and no double-time hats", mood: "Warm evening ease, plainspoken reflection, a communal singalong refrain, a short organ-and-guitar break, then a glowing fade", voice: "Singer A (Male), a relaxed midrange with Jamaican-leaning cadence, smoky tone and a memorable chorus", delivery: "Behind-the-beat melody, space between lines, a simple communal hook. No dancehall toasting marathon or pop belt", arrangement: "Offbeat guitar skank, round bass, one-drop drums and a bubble organ. Horns or keys answer the refrain. Drop to bass and guitar, then the chorus returns", production: "Warm analog mix, huge centered bass, airy high end. No trap 808, EDM snare rush, metal guitar or orchestral trailer" },
  "Soul R&B": { genre: "English, contemporary soul R&B with honest feeling, live-leaning pocket and a singer who knows when not to oversing", tempo: "86 BPM, E minor, slow 4/4 with a behind-the-beat pocket and no trap-hat grid", mood: "Low-lit confession, a held-back verse, an open-throated refrain, a quiet breakdown, then a last line that lands", voice: "Singer A (Female), a warm mezzo with chest-forward soul tone, controlled runs and close-mic intimacy", delivery: "Melodic verses, a memorable chorus, tasteful runs only at cadences. No belting contest, rap verse or gospel choir wall", arrangement: "Electric piano, round bass and a dry kit. Guitar or pad answers the vocal. Strip to keys and voice for the bridge, then the pocket returns", production: "Warm close mix, present vocal, modest stereo. No festival EDM, trap 808, country steel or orchestral swell" },
  Gospel: { genre: "English, contemporary gospel celebration with choir answers, organ and a joyful lift rather than pop-gospel crossover or quiet storm R&B", tempo: "108 BPM, E-flat major, mid-tempo 4/4 with a shouted refrain and a half-time testimony bridge", mood: "Gathering joy, a testimony verse, a communal shout-chorus, a brief hush, then a bigger last refrain", voice: "Singer A (Female), a powerful gospel mezzo with bright vowels, supported belt and call-and-response with a small choir", delivery: "Sung verses, a shoutable chorus, choir answers on the hook. No rap, metal grit or operatic Italianate line", arrangement: "Hammond-style organ, piano, bass and a live kit. Choir stacks the refrain. Drop to organ and lead for the bridge, then full ensemble", production: "Church-room bloom, present lead, wide choir. No trap hats, EDM drop, dark techno or dry lo-fi bedroom mix" },
  "Cafe bossa nova": { genre: "Portuguese-leaning bossa nova and sunny cafe jazz, nylon guitar and brushed swing rather than lounge electronica or pop-bossa parody", tempo: "92 BPM, D major, gently swung bossa 4/4 with a nylon-guitar pulse and no drum-machine grid", mood: "Late-morning light, easy conversation, a tender unforced refrain, a short guitar-and-voice break, then a smiling fade", voice: "Singer A (Female), a close soft mezzo with unhurried Portuguese-leaning vowels and behind-the-beat phrasing", delivery: "Quietly sung, space between lines, a simple refrain. No belting, scat marathon or English pop diction", arrangement: "Nylon guitar, upright bass, brushes and a light piano figure. A soft flute or voice-hum answers selected phrases. Drop to guitar and voice, then the combo returns", production: "Dry cafe recording, wooden-body bass, soft cymbals, present vocal. No trap, EDM, distortion or orchestral trailer", language: "pt" },
  "Contemporary folk": { genre: "English, contemporary folk and acoustic story-song with close guitar and unvarnished vocal rather than country-pop, Celtic pastiche or Nordic ritual folk", tempo: "98 BPM, G major, mid-tempo 4/4 with natural push-pull and no backbeat slam", mood: "Open-air honesty, a walking verse, a communal but quiet chorus, a short instrumental breath, then a last line on the road", voice: "Singer A (Female), a natural alto with conversational diction, light folk inflection and no pop belt", delivery: "Story-first melody, a simple chorus, optional one harmony on the last refrain. No rap, R&B melisma or theatrical diction", arrangement: "Acoustic guitar opens. Light upright or soft electric bass and brushed percussion enter. A second acoustic or mandolin answers the chorus. End on guitar and voice", production: "Honest room recording, detailed strings, modest compression. No 808, EDM, metal, orchestra or glossy Nashville pop" },
  "Heroic trailer cue": { genre: "English, heroic cinematic trailer cue with percussion, brass and a mission-to-victory arc rather than a full pop song or quiet piano score", tempo: "128 BPM, D minor into a brighter relative-major lift, driving 4/4 with a half-time hero hit", mood: "Starts with a mission, builds through obstacle, lands on somebody saving the kingdom", voice: "Instrumental; no pop vocal, rap or hummed melody. A small wordless choir may color the final hit only", arrangement: "Low strings and a ticking pulse open. Taikos and brass enter; a melody in horns at the midpoint. Biggest percussion-and-brass hit, then a short ringing tail", production: "Trailer-stage mix, huge transients, wide stereo, controlled low end. No trap hats, guitar solo, EDM supersaw drop or intimate jazz combo", instrumental: true },
  "Fantasy adventure cue": { genre: "English, fantasy adventure underscore with maps, doors and a quest that finally leaves the tavern, rather than trailer-only hits or pop-folk", tempo: "112 BPM, E minor, walking 4/4 with a 6/8 travel episode", mood: "Maps unfold, doors creak open, the quest finally leaves the tavern", voice: "Instrumental; no pop vocal. Optional distant wordless voices as texture only", arrangement: "Solo woodwind and harp over drones. Strings state a travel theme; light percussion for the road; a brief brass lift at the threshold, then a smaller coda", production: "Natural hall, realistic orchestra placement, no drum machine, electric guitar, trap or festival EDM", instrumental: true },
  "Bedtime lullaby": { genre: "English, soft bedtime lullaby for a small room, memorable enough for one more request rather than a pop ballad or ambient drone", tempo: "64 BPM, C major, slow 3/4 or gentle 4/4 with no backbeat", mood: "Soft enough for bedtime, a tiny memorable refrain, then a fade into sleep", voice: "Singer A (Female), a close quiet mezzo with narrow range, audible breath and no belt", delivery: "Soft sung phrases, lots of space, a simple repeating refrain. No rap, choir wall or theatrical vibrato", arrangement: "Celesta or soft piano, a round bass note, optional nylon guitar. No drums, or only a heartbeat-quiet pulse. End on a single instrument", production: "Very close, dark highs, tiny room. No club low end, EDM, metal or trailer percussion" },
  "Cute character theme": { genre: "English, cute character theme with three-note mascot energy and game-score sparkle rather than a full pop single or dark cinematic score", tempo: "132 BPM, F major, bouncy 4/4 with a playful stop-time hook", mood: "Three notes in and the mascot already has merchandise", voice: "Singer A (Female), a bright light voice with short playful phrases, or instrumental lead synth if sung lines stay tiny", delivery: "Short sung motifs, lots of instrumental answering. No long rap verse, opera or metal shout", arrangement: "Plucky synth or xylophone motif, bouncy bass, light drums. A brass or woodwind sting on the hook. Stop-time, then the motif returns", production: "Bright clean mix, modest stereo, no dark industrial, trap 808 or trailer boom" },
  "80s hair band": { genre: "English, 1980s glam metal hair-band rock with twin leads, gang-shout choruses and arena drums rather than modern metalcore, grunge or pop-punk", tempo: "126 BPM, E minor, driving 4/4 with a half-time fist-pump chorus", mood: "Midnight backstage bravado, a verse that struts, a huge communal shout-chorus, a guitar-hero break, then a last-hold-the-note finish", voice: "Singer A (Male), a high raspy glam-metal tenor with open vowels, a screaming-sung belt and a memorable gang-ready hook", delivery: "Sung verses with attitude, a shouted-sung chorus the crowd can yell, no rap and no quiet-storm R&B", arrangement: "Crunch rhythm guitars and a snare-forward kit from bar one. Harmony lead guitar answers the vocal. Gang vocals on the chorus. A dual-guitar solo, then the final shout", production: "Huge 80s arena rock mix, gated snare, stacked guitars, vocal-forward. No djent, trap 808, EDM drop or lo-fi bedroom mix" },
  "80s techno": { genre: "English, 1980s techno and early warehouse electronics with analog drum machines and acid-leaning bass rather than modern big-room EDM, trance supersaws or house four-on-the-floor gloss", tempo: "128 BPM, A minor, straight 4/4 machine groove with a hypnotic 16th-hat grid", mood: "After-hours concrete, a cold hypnotic hook, a filter-open break, then a drier last loop", voice: "Singer A (Female), a detached close electro-pop mezzo, short repeated phrases, no belting ballad", delivery: "Sparse sung or spoken-sung hooks locked to the machine. No gospel runs, rap verses or rock scream", arrangement: "Analog kick, snare and a repeating bass sequence from the start. A stabby synth answers the hook. Strip to drums and bass, then the sequence returns brighter", production: "Dry warehouse electronics, punchy kick, modest stereo, tape-era synths. No festival EDM, metal guitar, trap hats or orchestral trailer" },
};
